### ISSUE TITLE
Altair v.5.0.0

### ISSUE THREAD

**Issue by Negatil07** [Alex2262/AltairChessEngine#163]
Problem running on Chess Cli
in Termux terminal but in Droidfish no problem.

libc++abi: terminating due to uncaught exception of type std::invalid_argument: stoi: no conversion
[1] could not read from Altair.v.5.0.0

**Comment by Alex2262** [comment]
Hi,
Is the issue with cutechess-cli? I haven't heard of a "Chess Cli".
Either way, I would assume Altair 5.0.0 handles UCI perfectly fine with a correct CLI / GUI as it was tested for hundreds and thousands of games using the cutechess-cli, GUIs, and rating lists such as CCRL.

Altair 5.0.0 will not be receiving further updates; however, I am happy to help if there's any other way that I can, e.g. using a CLI to run Altair.
