### ISSUE TITLE
Puzzle

### ISSUE THREAD

**Issue by Negatil07** [Alex2262/AltairChessEngine#165]
![Screenshot_20240310-191752](https://github.com/Alex2262/AltairChessEngine/assets/97826921/08bfe7b5-f4ff-4a7c-be24-be7ab6f6ccd5)

Cannot find mate.

Android Nougat
Droidfish Gui

Chess for Android = not compatible

**Comment by Alex2262** [comment]
Hi,

It is expected that Altair will be unable to solve certain positions. I cannot do anything specifically about this issue, as developing an engine based on certain positions is not good. If I were to change parts of the engine that would allow Altair to solve this position, it would most likely compromise other parts of the engine. Engines are tested and developed off of large random samples of games, and tested for superiority. Testing based on one position wouldn't give any meaningful results about the engine's overall progression.

As an engine becomes stronger, it is expected that it will solve more positions, and possibly puzzles such as this one. However, an engine can never be perfect, and it will also fail to solve certain positions such as the one you have shown. Engines such as Stockfish still aren't able to solve certain puzzles completely accurately.
