### ISSUE TITLE
Please add ARMv9.2, SVE2, Dot Product and Neon support

### ISSUE THREAD

**Issue by Chess321** [Alex2262/AltairChessEngine#168]
It's sad that it's not possible to compile the newest version on Android and Linux devices.

**Comment by Alex2262** [comment]
Altair can definitely be compiled on Linux and Arm devices as I have done so myself. It may not be possible to compile Altair on Android devices, as I do not have on and thus cannot test on it. It is also not my priority to support it currently. As for NEON, Altair does compile with NEON; however, auto-vectorization is used in place of the handmade NEON SIMD code as it is faster.
