### ISSUE TITLE
multi-threading and multiple CPUs : new in v3.0.0 ?

### ISSUE THREAD

**Issue by tissatussa** [Alex2262/AltairChessEngine#46]
> Altair now supports multi-threading and the usage of multiple CPUs to make it stronger

You write this at the release page of v3.0.0, but i don't understand : previous version v2.0.0 had an UCI option called 'Threads' and so does v3.0.0 .. can you explain ?

**Comment by tissatussa** [comment]
OK, i must be referencing a compiled dev version, i don't remember .. tnx.

**Comment by Alex2262** [comment]
no problem :)
